name: ProteinDJ Upstream Traffic

on:
  schedule:
    - cron: "55 23 * * 0"
  workflow_dispatch: {}

jobs:
  traffic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "traffic"

      - name: Repository Traffic
        uses: sangonzal/repository-traffic-action@v.0.1.6
        env:
          TRAFFIC_ACTION_TOKEN: ${{ secrets.TRAFFIC_ACTION_TOKEN }}
          REPOSITORY_NAME: "PapenfussLab/ProteinDJ"

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: "Josh Hardy"
          message: "Update ProteinDJ upstream traffic data"
          add: "./traffic/*"
          ref: "traffic"